sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t ntb19132/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ntb19132/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-099508042811"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
