sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t ntb19132/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ntb19132/docker-react npm run test
